# Generated by Django 5.0.6 on 2024-08-29 10:27

from django.db import migrations

def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    categories = [
        {"name": "Electronics", "description": "Electronic devices and accessories"},
        {"name": "Clothing", "description": "Apparel and fashion items"},
        {"name": "Books", "description": "Books and publications"},
    ]
    for category in categories:
        Category.objects.create(**category)

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sales'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories),
    ]
