# Generated by Django 5.0.6 on 2024-08-29 10:46

from django.db import migrations

def add_initial_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    categories = [
        'Electronics',
        'Clothing',
        'Books',
        'Home & Garden',
        'Toys & Games'
    ]
    for category_name in categories:
        Category.objects.create(name=category_name)

def remove_initial_categories(apps, schema_editor):
    Category = apps.get_model('products', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20240829_1027'),
    ]

    operations = [
        migrations.RunPython(add_initial_categories, remove_initial_categories),
    ]
