# Generated by Django 4.2.14 on 2025-02-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_low_stock_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='product_qr_codes/'),
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
