# Generated by Django 4.2.14 on 2024-10-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('cost_of_services', 'Cost of Services')], max_length=20),
        ),
    ]
