# Generated by Django 4.2.14 on 2024-10-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('salary', 'Salary'), ('marketing_expenses', 'Marketing Expenses'), ('office_supplies', 'Office Supplies'), ('utilities', 'Utilities'), ('other', 'Other'), ('cost_of_services', 'Cost of Services')], max_length=50, null=True),
        ),
    ]
