# Generated by Django 4.2.14 on 2025-01-11 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0004_alter_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('income', 'Income'), ('salary', 'Salary'), ('marketing_expenses', 'Marketing Expenses'), ('office_supplies', 'Office Supplies'), ('utilities', 'Utilities'), ('other', 'Other'), ('cost_of_services', 'Cost of Services')], max_length=50, null=True),
        ),
    ]
