# Generated by Django 4.2.14 on 2025-03-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreAddress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'core_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreCompanyinfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'core_companyinfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreCustomer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'core_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreOrder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('order_date', models.DateTimeField()),
                ('shipped_date', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.IntegerField()),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True)),
                ('special_instructions', models.TextField()),
                ('status', models.CharField(max_length=20)),
                ('tracking_number', models.CharField(max_length=100)),
                ('previous_status', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'core_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreOrderitem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customization', models.TextField()),
            ],
            options={
                'db_table': 'core_orderitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreOrderpromotion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'core_orderpromotion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CorePromotion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'core_promotion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreVisit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=64)),
                ('ip_address', models.CharField(blank=True, max_length=39, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer_url', models.CharField(blank=True, max_length=2000, null=True)),
                ('visited_url', models.CharField(max_length=2000)),
                ('timestamp', models.DateTimeField()),
                ('geo_location', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'core_visit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoicesInvoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('invoice_number', models.CharField(max_length=32, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'invoices_invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvoicesInvoiceitem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'invoices_invoiceitem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'products_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsProduct',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('stock', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
                ('sales', models.PositiveIntegerField()),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'products_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsProductimage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=100)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'products_productimage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'products_review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportsCalculatedfield',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('formula', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'reports_calculatedfield',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportsReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_archived', models.IntegerField()),
                ('is_template', models.IntegerField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('schedule', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'reports_report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportsReportaccesslog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('accessed_at', models.DateTimeField()),
                ('action', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'reports_reportaccesslog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportsReportentry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 'reports_reportentry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReportsReportfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField()),
                ('file_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'reports_reportfile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentsStockadjustment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('adjustment_date', models.DateField()),
                ('adjustment_type', models.CharField(max_length=10)),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'stock_adjustments_stockadjustment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionsTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('transaction_type', models.CharField(max_length=20)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'transactions_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersCustomuser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'users_customuser',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersCustomuserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users_customuser_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersCustomuserRoles',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users_customuser_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersCustomuserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users_customuser_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersInsight',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users_insight',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersPermission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'users_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersPermissionauditlog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('resource', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users_permissionauditlog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersPermissionchangelog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_roles', models.TextField()),
                ('new_roles', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'users_permissionchangelog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.IntegerField()),
            ],
            options={
                'db_table': 'users_role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersRolePermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users_role_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersUserpreference',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dark_mode', models.IntegerField()),
                ('notification_frequency', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'users_userpreference',
                'managed': False,
            },
        ),
    ]
