# Generated by Django 4.2.14 on 2024-09-15 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address_created_address_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='billing_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_customer', to='core.address'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='core.address'),
        ),
    ]
