# Generated by Django 4.2.14 on 2024-09-27 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_orderitem_product_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='previous_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
