# Generated by Django 4.2.14 on 2024-10-05 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_invoiceitem_product'),
        ('core', '0008_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_order', to='invoices.invoice'),
        ),
    ]
