# Generated by Django 4.2.14 on 2024-10-05 13:14

from django.db import migrations


def populate_order_user(apps, schema_editor):
    Order = apps.get_model('core', 'Order')
    Customer = apps.get_model('core', 'Customer')
    
    for order in Order.objects.filter(user__isnull=True):
        try:
            customer = Customer.objects.get(id=order.customer_id)
            order.user = customer.user
            order.save()
        except Customer.DoesNotExist:
            print(f"Customer not found for order {order.id}")
        except AttributeError:
            print(f"Customer has no user for order {order.id}")

def reverse_populate_order_user(apps, schema_editor):
    Order = apps.get_model('core', 'Order')
    Order.objects.all().update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order_user'),
    ]

    operations = [
        migrations.RunPython(populate_order_user, reverse_populate_order_user),
    ]
