# Generated by Django 4.2.14 on 2024-10-14 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_populate_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the session.', unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the visitor.', null=True)),
                ('user_agent', models.TextField(blank=True, help_text="User agent string of the visitor's browser.", null=True)),
                ('referrer_url', models.URLField(blank=True, help_text='URL of the page that referred the visitor.', null=True)),
                ('visited_url', models.URLField(help_text='URL that was visited.')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time of the visit.')),
                ('geo_location', models.CharField(blank=True, help_text='Geographical location of the visitor based on IP.', max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, help_text='Type of device used (e.g., Mobile, Tablet, Desktop).', max_length=50, null=True)),
                ('operating_system', models.CharField(blank=True, help_text="Operating system of the visitor's device.", max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Authenticated user associated with the visit (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visit',
                'verbose_name_plural': 'Visits',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='core_visit_timesta_4f8041_idx'), models.Index(fields=['user'], name='core_visit_user_id_e02fbb_idx'), models.Index(fields=['session_id'], name='core_visit_session_55980b_idx'), models.Index(fields=['ip_address'], name='core_visit_ip_addr_ed214c_idx')],
            },
        ),
    ]
