# Generated by Django 4.2.14 on 2024-11-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_visit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visited_url',
            field=models.URLField(help_text='URL that was visited.', max_length=2000),
        ),
    ]
