# Generated by Django 4.2.14 on 2024-11-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_visit_visited_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='session_id',
            field=models.CharField(db_index=True, help_text='Session identifier for the visit.', max_length=64),
        ),
        migrations.AlterField(
            model_name='visit',
            name='referrer_url',
            field=models.URLField(blank=True, help_text='URL of the page that referred the visitor.', max_length=2000, null=True),
        ),
    ]
