# Generated by Django 4.2.14 on 2024-11-20 14:25

from django.db import migrations, connection, models

def drop_session_index(apps, schema_editor):
    with connection.cursor() as cursor:
        # Check and drop `core_visit_session_id_46766cf2` if it exists
        cursor.execute(
            """
            SELECT COUNT(*) 
            FROM INFORMATION_SCHEMA.STATISTICS 
            WHERE TABLE_NAME = 'core_visit' AND INDEX_NAME = 'core_visit_session_id_46766cf2'
            """
        )
        if cursor.fetchone()[0] > 0:
            cursor.execute("DROP INDEX core_visit_session_id_46766cf2 ON core_visit")

def recreate_session_index(apps, schema_editor):
    with connection.cursor() as cursor:
        # Recreate the index for rollback
        cursor.execute("CREATE INDEX core_visit_session_id_46766cf2 ON core_visit (session_id)")

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0014_remove_visit_core_visit_session_55980b_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(drop_session_index, recreate_session_index),
        migrations.AlterField(
            model_name='visit',
            name='session_id',
            field=models.CharField(
                max_length=64,
                db_index=True,
                help_text="Session identifier for the visit.",
                unique=False  # Ensure no unique constraint
            ),
        ),
    ]
