# Generated by Django 4.2.14 on 2024-11-20 14:32

from django.db import migrations, connection, models
from django.conf import settings

def drop_indexes(apps, schema_editor):
    # List of indexes to drop
    indexes_to_drop = [
        'core_visit_timesta_4f8041_idx',
        'core_visit_timestamp_2ec1c6f3',
        'core_visit_ip_addr_ed214c_idx',
    ]

    with connection.cursor() as cursor:
        for index in indexes_to_drop:
            cursor.execute(
                """
                SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.STATISTICS 
                WHERE TABLE_NAME = 'core_visit' AND INDEX_NAME = %s
                """,
                [index]
            )
            if cursor.fetchone()[0] > 0:
                cursor.execute(f"DROP INDEX {index} ON core_visit")

def recreate_indexes(apps, schema_editor):
    # Recreate the indexes for rollback
    with connection.cursor() as cursor:
        cursor.execute("CREATE INDEX core_visit_timesta_4f8041_idx ON core_visit (timestamp)")
        cursor.execute("CREATE INDEX core_visit_timestamp_2ec1c6f3 ON core_visit (timestamp)")
        cursor.execute("CREATE INDEX core_visit_ip_addr_ed214c_idx ON core_visit (ip_address)")

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_remove_visit_core_visit_session_55980b_idx'),
    ]

    operations = [
        migrations.RunPython(drop_indexes, recreate_indexes),
        migrations.AlterField(
            model_name='visit',
            name='timestamp',
            field=models.DateTimeField(
                db_index=True,
                default=models.functions.Now(),
                help_text="Date and time of the visit."
            ),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=models.SET_NULL,
                related_name='visits',
                db_index=True,
                to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip_address',
            field=models.GenericIPAddressField(
                null=True,
                blank=True,
                db_index=True
            ),
        ),
    ]
