# Generated by Django 4.2.14 on 2024-11-21 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_remove_visit_core_visit_session_55980b_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='visit',
            name='core_visit_session_55980b_idx',
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of the visitor.', null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date and time of the visit.'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Authenticated user associated with the visit (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to=settings.AUTH_USER_MODEL),
        ),
    ]
