# Generated by Django 4.2.14 on 2025-01-08 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_remove_visit_core_visit_session_55980b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sales_rep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_category',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('cost_of_services', 'Cost of Services')], default='income', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.customer'),
        ),
    ]
