# Generated by Django 4.2.14 on 2025-01-08 13:26

from django.db import migrations


def forward_func(apps, schema_editor):
    Order = apps.get_model('core', 'Order')
    for order in Order.objects.all():
        order.sales_rep = order.user
        order.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_order_sales_rep_order_transaction_category_and_more'),
    ]

    operations = [
        migrations.RunPython(forward_func, reverse_func),
    ]
