# Generated by Django 4.2.14 on 2025-01-08 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0019_populate_sales_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sales_rep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
