# Generated by Django 4.2.14 on 2025-02-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_order_sales_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_scanned_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
