# Generated by Django 4.2.14 on 2024-11-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_insight_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='category',
            field=models.CharField(choices=[('USER', 'User Management'), ('ROLE', 'Role Management'), ('RESOURCE', 'Resource Access'), ('SYSTEM', 'System Configuration')], default='USER', max_length=50),
        ),
        migrations.AddField(
            model_name='permission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
