# Generated by Django 5.0.6 on 2024-09-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_adjustments', '0004_alter_stockadjustment_adjustment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='adjustment_type',
            field=models.CharField(choices=[('ADD', 'Add'), ('REMOVE', 'Remove'), ('RETURN', 'Return'), ('DAMAGE', 'Damage')], max_length=10),
        ),
    ]
