# Generated by Django 4.2.14 on 2025-02-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_adjustments', '0005_alter_stockadjustment_adjustment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='stock_adjustments/qr_codes/'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='qr_code_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
