# Generated by Django 4.2.14 on 2024-12-12 17:32

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_reportentry_options_report_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF Document'), ('excel', 'Excel Spreadsheet'), ('csv', 'CSV File'), ('other', 'Other File Type')], default='pdf', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportfile',
            name='file',
            field=models.FileField(max_length=255, upload_to=reports.models.report_file_path),
        ),
    ]
