# Generated by Django 4.2.14 on 2024-12-18 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportfile_file_type_alter_reportfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(message='Invalid name format', regex='^[A-Za-z0-9\\s\\-_]+$')], verbose_name='Report Name'),
        ),
    ]
