# Generated by Django 4.2.14 on 2024-12-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportaccesslog',
            options={'ordering': ['-accessed_at']},
        ),
        migrations.AddField(
            model_name='reportaccesslog',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
