# Generated by Django 4.2.14 on 2025-01-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_reportaccesslog_email_reportaccesslog_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='reportaccesslog',
            name='reports_rep_user_id_991ab3_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportaccesslog',
            name='reports_rep_accesse_984cf1_idx',
        ),
        migrations.RemoveIndex(
            model_name='reportaccesslog',
            name='reports_rep_action_5768ef_idx',
        ),
        migrations.RemoveField(
            model_name='reportaccesslog',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reportaccesslog',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='reportaccesslog',
            name='action',
            field=models.CharField(max_length=50),
        ),
    ]
