# Generated by Django 4.2.14 on 2024-09-11 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_alter_invoice_invoice_number'),
    ]

    operations = [
    ]
