# Generated by Django 4.2.14 on 2024-09-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_created_product_created_at_and_more'),
        ('invoices', '0010_invoice_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='products.product'),
        ),
    ]
