# Generated by Django 4.2.14 on 2025-02-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_invoiceitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='invoice_qr_codes/'),
        ),
    ]
